version = 0.1

[default.global.parameters]
stack_name = "sam-users-crud-ts"

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
resolve_s3 = true
s3_prefix = "sam-users-crud-ts"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
fail_on_empty_changeset = false
image_repositories = []